[[domain]]
name = "emanon.moe"
api_key = ""

  # [[domain.record]]
  #   name = "@"
  #   type = "A"
  #   ttl = 1200

  [[domain.record]]
    name = "rust"
    type = "AAAA"
    ttl = 300

  [[domain.record]]
    name = "tesvfft"
    type = "AAAA"
    ttl = 300
