[[domain]]
name = ""
api_key = ""

  [[domain.record]]
    name = "@" # the domain itself
    type = "A"
    ttl = 1200

  [[domain.record]]
    name = "rust"  # subdomain
    type = "AAAA"
    ttl = 1200
